name: Compile Java Backend

on: [push, pull_request]

jobs:
  compile-backend:
    runs-on: ubuntu-latest
    name: Compile Backend Code
    steps:
      - uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Compile with Maven
        run: |
          cd app
          mvn clean compile
