name: Lint Dockerfiles

on: [push, pull_request]

jobs:
  dockerlint:
    runs-on: ubuntu-latest
    name: Lint Dockerfiles
    steps:
      - uses: actions/checkout@v5

      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./app/Dockerfile
